package com.isuara.app.emotion

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Locks [EmotionPreprocessor] to the tensor EmotiEffLib's own pipeline produces.
 *
 * This is the highest-value test in the emotion path, because every way this
 * code can be wrong is silent. Swap the channel order, drop the /255, or use the
 * wrong normalisation constants and nothing throws — the model simply returns
 * confident, plausible, wrong emotions that no other test would notice.
 *
 * The fixture in `src/test/resources/emotion/` was generated by
 * `tools/emotion_preprocess_golden.py`, which runs the reference preprocessing
 * from EmotiEffLib against the real ONNX graph. Regenerate it there, never by
 * hand, and never by copying values out of a failing assertion.
 *
 * The test image is defined in closed form by [synthetic] rather than shipped as
 * a PNG: it keeps the fixture tiny, avoids depending on Android's image decoder
 * from a JVM test, and sidesteps licensing a face photo into the repository.
 */
class EmotionPreprocessorTest {

    private companion object {
        /** Wider than float32 rounding, far tighter than any real mistake. */
        const val TOLERANCE = 1e-4f
    }

    private fun golden(): JSONObject {
        val stream = javaClass.classLoader!!
            .getResourceAsStream("emotion/emotion_preprocess_golden.json")
        requireNotNull(stream) { "golden fixture missing from test resources" }
        return JSONObject(stream.bufferedReader().use { it.readText() })
    }

    /**
     * The reference image, as ARGB_8888 ints.
     *
     * Each channel occupies its own value band on purpose. If the channels
     * overlapped, a red/blue swap would leave the per-channel statistics almost
     * unchanged and this test would pass while the model quietly degraded — an
     * earlier version of the fixture had exactly that flaw.
     */
    private fun synthetic(): IntArray {
        val size = EmotionPreprocessor.INPUT_SIZE
        val out = IntArray(size * size)
        for (y in 0 until size) {
            for (x in 0 until size) {
                val r = (x * 7 + y * 13) % 60
                val g = 90 + ((x * 3 + y * 29) % 60)
                val b = 190 + ((x * 17 + y * 5) % 60)
                out[y * size + x] = (0xFF shl 24) or (r shl 16) or (g shl 8) or b
            }
        }
        return out
    }

    private fun channelMean(t: FloatArray, c: Int): Float {
        var sum = 0.0
        val base = c * EmotionPreprocessor.PLANE
        for (i in 0 until EmotionPreprocessor.PLANE) sum += t[base + i]
        return (sum / EmotionPreprocessor.PLANE).toFloat()
    }

    @Test
    fun `tensor matches the EmotiEffLib reference`() {
        val g = golden()
        val tensor = EmotionPreprocessor.toTensor(synthetic())

        assertEquals(g.getInt("tensor_length"), tensor.size)

        val means = g.getJSONArray("channel_mean")
        val mins = g.getJSONArray("channel_min")
        val maxs = g.getJSONArray("channel_max")
        for (c in 0 until 3) {
            assertEquals(
                "channel $c mean",
                means.getDouble(c).toFloat(), channelMean(tensor, c), TOLERANCE,
            )
            val base = c * EmotionPreprocessor.PLANE
            val plane = tensor.copyOfRange(base, base + EmotionPreprocessor.PLANE)
            assertEquals("channel $c min", mins.getDouble(c).toFloat(), plane.min(), TOLERANCE)
            assertEquals("channel $c max", maxs.getDouble(c).toFloat(), plane.max(), TOLERANCE)
        }

        val spots = g.getJSONObject("spot_values")
        for (key in spots.keys()) {
            assertEquals(
                "tensor[$key]",
                spots.getDouble(key).toFloat(), tensor[key.toInt()], TOLERANCE,
            )
        }
    }

    /**
     * Guards the specific mistake the fixture exists to catch. EmotiEffLib's
     * preprocess function contains no colour conversion, which makes it look
     * like it wants BGR; its test suite converts to RGB before calling. Getting
     * this backwards is the single most likely error in this file.
     */
    @Test
    fun `fixture would reject a swapped channel order`() {
        val g = golden()
        assertEquals("RGB", g.getString("channel_order"))

        val swapped = synthetic().map { argb ->
            val r = (argb shr 16) and 0xFF
            val b = argb and 0xFF
            (0xFF shl 24) or (b shl 16) or (argb and 0x00FF00) or r
        }.toIntArray()
        val tensor = EmotionPreprocessor.toTensor(swapped)

        val expectedR = g.getJSONArray("channel_mean").getDouble(0).toFloat()
        assertNotEquals(
            "a red/blue swap must not pass the mean check",
            expectedR.toDouble(), channelMean(tensor, 0).toDouble(), 0.5,
        )
    }

    @Test
    fun `rejects a wrongly sized image`() {
        val tooSmall = IntArray(16)
        val e = runCatching { EmotionPreprocessor.toTensor(tooSmall) }.exceptionOrNull()
        assertTrue("expected IllegalArgumentException, got $e", e is IllegalArgumentException)
    }

    @Test
    fun `softmax normalises logits to a distribution`() {
        val probs = EmotionPreprocessor.softmax(floatArrayOf(1f, 2f, 3f, 4f, 5f, 6f, 7f, 8f))
        assertEquals(1f, probs.sum(), 1e-5f)
        assertEquals(7, EmotionAggregator.argmax(probs))
        assertTrue(probs.all { it > 0f })
    }

    /** Max-shifting is what keeps this from overflowing to NaN. */
    @Test
    fun `softmax survives large logits`() {
        val probs = EmotionPreprocessor.softmax(floatArrayOf(1000f, 1001f, 999f))
        assertEquals(1f, probs.sum(), 1e-5f)
        assertTrue(probs.none { it.isNaN() })
    }

    /** The reference probabilities in the fixture are a distribution too. */
    @Test
    fun `reference logits softmax to the reference probabilities`() {
        val g = golden()
        val logitsJson = g.getJSONArray("reference_logits_rgb")
        val logits = FloatArray(logitsJson.length()) { logitsJson.getDouble(it).toFloat() }
        assertEquals(EmotionLabel.COUNT, logits.size)

        val probs = EmotionPreprocessor.softmax(logits)
        val expected = g.getJSONArray("reference_probs_rgb")
        for (i in probs.indices) {
            assertEquals(expected.getDouble(i).toFloat(), probs[i], TOLERANCE)
        }
    }
}
